FROM tiangolo/uwsgi-nginx:python3.8-alpine
RUN apk --update add bash nano
ENV STATIC_URL /static
ENV STATIC_PATH /var/www/app/static
COPY ./requirements.txt /var/www/requirements.txt
RUN apk add --no-cache build-base mariadb-connector-c-dev
RUN pip install -r /var/www/requirements.txt
